# Use an official Node.js runtime
FROM node:22-alpine

# Set working directory
WORKDIR /app


COPY package*.json ./

# Install dependencies
RUN npm install


COPY . .


# Expose the port
EXPOSE 3000

# Start the app
CMD ["node", "server.js"]
